version: "3.8"

services:
  app:
    container_name: guatis-api
    working_dir: /code
    volumes:
      - ./api:/code
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    environment:
      OPENAI_KEY: ${OPENAI_KEY}
